openapi: 3.0.0
info:
  title: Pet
  version: 1.0.0

servers:
  - url: http://localhost:3031

paths:
  /pets:
    get:
      operationId: getPets
      responses:
        '200':
          description: A lot of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
    post:
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required: ["name"]
      responses:
        '200':
          description: The newly created pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'

  /pets/{petId}/picture:
    post:
      operationId: uploadPetPicture
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            additionalProperties: false
      responses:
        '200':
          description: Nothing

  /pets/{petId}:
    get:
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            additionalProperties: false
      responses:
        '200':
          description: A single pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'
        '400':
          description: Pet does not exist

components:
  schemas:
    pet:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        breed:
          type: string
          enum: ['dalmatian', 'dachshund']
        food:
          $ref: '#/components/schemas/food'
      required: ['id', 'name']
      additionalProperties: false
    food:
      type: object
      properties:
        name:
          type: string
      required: ['name']
      additionalProperties: false
