openapi: 3.0.0
info:
  title: Pet
  version: 1.0.0

servers:
  - url: http://localhost:3031

paths:
  /http:
    get:
      operationId: get
      responses:
        '200':
          description: Test http operation
    put:
      operationId: put
      responses:
        '200':
          description: Test http operation
    post:
      operationId: post
      responses:
        '200':
          description: Test http operation
    delete:
      operationId: delete
      responses:
        '200':
          description: Test http operation
    patch:
      operationId: patch
      responses:
        '200':
          description: Test http operation

  /validation/query:
    get:
      operationId: validationQuery
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test query parameter validation
          content:
            application/json:
              schema:
                type: object
                properties:
                  query: 
                    type: string

  /features/component-responses:
    get:
      operationId: featureComponentResponses
      responses:
        '400':
          $ref: '#/components/responses/Unauthorized'
  /features/file-upload:
    post:
      operationId: featureFileUpload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: ['file']
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Nothing
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string

  /pets:
    get:
      operationId: getPets
      responses:
        '200':
          description: A lot of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required: ['name']
      responses:
        '200':
          description: The newly created pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

  /pets/default-responses:
    get:
      operationId: defaultResponses
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'

  /pets/{petId}/picture:
    post:
      operationId: uploadPetPicture
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            additionalProperties: false
      responses:
        '200':
          description: Nothing

  /pets/{petId}:
    get:
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            additionalProperties: false
      responses:
        '200':
          description: A single pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Pet does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required: ['message']


components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        breed:
          type: string
          enum: ['dalmatian', 'dachshund']
        food:
          $ref: '#/components/schemas/Food'
      required: ['id', 'name']
      additionalProperties: false
    Food:
      type: object
      properties:
        name:
          type: string
      required: ['name']
      additionalProperties: false
    ServerError:
      type: object
      required: ['errors']
      properties:
        errors:
          type: array
          items:
            type: object
            required: ['message']
            properties:
              message:
                type: string

  responses:
    Unauthorized:
      description: You are not authorized to perform this action
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerError'